[project]
name="sku_formatter"
version="1.0.0"
requires-python=">=3.10"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.scripts]
skuf="sku_formatter.__main__:main"

[tool.setuptools.packages.find]
where=["src"]

[tool.pytest.ini_options]
addopts=[
    "--import-mode=importlib",
]

[project.optional-dependencies]
test = ["pytest"]